### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-branding-page#21]

**Comment by purohitdheeraj** [comment]
Hello @Neha can you please assign this to me

**Comment by purohitdheeraj** [comment]
hey i just created a pull request for contributing guidelines can you please review it, feel free to suggest changes

https://github.com/jslovers/jslovers-branding-page/pull/22#issue-1965993987

**Comment by Neha** [comment]
Thank you @purohitdheeraj , I will review the PR.
