### ISSUE TITLE
Add sponsors logo

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-branding-page#7]
Add sponsors logo to the webapge

**Comment by unnati611** [comment]
@Neha I want to pick this can you share page where we have ti add this

**Comment by MehakMantri** [comment]
May I kindly request permission to work on this issue? 
If you're open to it, I'm ready to get started.

**Comment by Neha** [comment]
> @Neha I want to pick this can you share the page where we have to add this

Thank you @unnati611. 

On the HTML page...there is a section for sponsors and the names of the companies too. You can add there

**Comment by Neha** [comment]
> May I kindly request permission to work on this issue? If you're open to it, I'm ready to get started.

Thank you @MehakMantri. I have assigned this issue to @unnati611 as she commented first. You can pick some other issues.

**Comment by unnati611** [comment]
@Neha please check this 
![image](https://github.com/jslovers/jslovers-branding-page/assets/148221914/44c13ac2-b5a9-428a-94de-24ff566e3973)
 if it is ok than i will fixed it

**Comment by Neha** [comment]
Thank you @unnati611.

Can we have a hover effect on the logo, please?  By default, we can have non-colour logo (eg: we can use a CSS filter) and on hover original logo will appear.

Let me know if you have any question
