### ISSUE TITLE
Design new JSLovers logo

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-branding-page#8]
Add the JSLovers logo to be downloaded by anyone who wants to use it :

1. Different sizes and formats
2. Different background colors, and logo

**Comment by SahulKola** [comment]
Hey Neha,
I just thought to revamp the whole logo.
Please let me know if any changes

Will finalize and add all these variations along with favicons in the repo.
# Logos
<img width="957" alt="image" src="https://github.com/jslovers/jslovers-branding-page/assets/39924419/3a54e0a4-db2f-4ad0-a342-c539e9281118">

**Comment by Neha** [comment]
Thank you @SahulKola. These looks lovely. Let me review the logos and share the feedback with you.

**Comment by Neha** [comment]
Hey @SahulKola ,  A few suggestions:

1. There is no space between JS and Lovers. So, it should be JSLovers
2. Can you create a version where we have the text under the square?
3. Can you please create a version  in `#1d4ca1 `color

**Comment by SahulKola** [comment]
Hey @Neha 
Here are the versions

<img width="487" alt="image" src="https://github.com/jslovers/jslovers-branding-page/assets/39924419/25851b0a-bb5f-4711-b9e0-fb24be123d55">

**Comment by Neha** [comment]
Thank you. I think the first design suggestion was looking better. 

Can we change the yellow to blue colour.

**Comment by SahulKola** [comment]
Sure, Here are two variations
<img width="533" alt="image" src="https://github.com/jslovers/jslovers-branding-page/assets/39924419/427ba627-0007-4e29-b959-8040e9e7760e">

**Comment by Neha** [comment]
@SahulKola  thank you so much. I have asked the folks over discord to share their view. Give it a few days, please.

**Comment by Neha** [comment]
We have got the new logo. Thank you for help
